module RuboCop
  module Cop
    class Base
      def on_new_investigation: () -> void
      def on_investigation_end: () -> void
    end

    module RangeHelp
      def range_between: (Integer start_pos, Integer end_pos) -> Parser::Source::Range
    end
  end
end
