plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 20

Naming/FileName:
  Exclude:
    - lib/rubocop-rbs_inline.rb

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

# for RBS::Inline
Layout/LeadingCommentSpace:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false
