plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rbs_inline

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - bin/**/*
    - vendor/**/*

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 20

Naming/FileName:
  Exclude:
    - lib/rubocop-rbs_inline.rb

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

# for RBS::Inline
Layout/LeadingCommentSpace:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

# rubocop-rbs_inline configuration
Style/RbsInline/MissingTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation

Style/RbsInline/RedundantTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation

Style/RbsInline/RequireRbsInlineComment:
  EnforcedStyle: never
