# frozen_string_literal: true

require_relative 'style/rbs_inline/source_code_helper'
require_relative 'style/rbs_inline/comment_parser'
require_relative 'style/rbs_inline/embedded_rbs_spacing'
require_relative 'style/rbs_inline/invalid_comment'
require_relative 'style/rbs_inline/invalid_types'
require_relative 'style/rbs_inline/keyword_separator'
require_relative 'style/rbs_inline/method_comment_spacing'
require_relative 'style/rbs_inline/data_class_comment_alignment'
require_relative 'style/rbs_inline/missing_data_class_annotation'
require_relative 'style/rbs_inline/missing_type_annotation'
require_relative 'style/rbs_inline/parameters_separator'
require_relative 'style/rbs_inline/redundant_annotation_with_skip'
require_relative 'style/rbs_inline/redundant_type_annotation'
require_relative 'style/rbs_inline/require_rbs_inline_comment'
require_relative 'style/rbs_inline/unmatched_annotations'
require_relative 'style/rbs_inline/variable_comment_spacing'
