# frozen_string_literal: true

# Mixins first, in dependency order. Cops follow, alphabetically: `rake new_cop` sorts a
# generated require only against the others in the same directory, so the two blocks have
# to stay apart for it to land in the right place.
require_relative "style/rbs_inline/mixin/annotation_keywords"
require_relative "style/rbs_inline/mixin/ast_utils"
require_relative "style/rbs_inline/mixin/source_code_helper"
require_relative "style/rbs_inline/mixin/comment_parser"
require_relative "style/rbs_inline/mixin/data_struct_helper"
require_relative "style/rbs_inline/mixin/missing_class_annotation"
require_relative "style/rbs_inline/mixin/class_comment_alignment"
require_relative "style/rbs_inline/mixin/data_class_matcher"
require_relative "style/rbs_inline/mixin/file_filter"
require_relative "style/rbs_inline/mixin/struct_class_matcher"

require_relative "style/rbs_inline/data_class_comment_alignment"
require_relative "style/rbs_inline/data_define_with_block"
require_relative "style/rbs_inline/embedded_rbs_spacing"
require_relative "style/rbs_inline/invalid_comment"
require_relative "style/rbs_inline/invalid_types"
require_relative "style/rbs_inline/keyword_separator"
require_relative "style/rbs_inline/method_comment_spacing"
require_relative "style/rbs_inline/missing_data_class_annotation"
require_relative "style/rbs_inline/missing_struct_class_annotation"
require_relative "style/rbs_inline/missing_type_annotation"
require_relative "style/rbs_inline/parameters_separator"
require_relative "style/rbs_inline/redundant_annotation_with_skip"
require_relative "style/rbs_inline/redundant_instance_variable_annotation"
require_relative "style/rbs_inline/redundant_type_annotation"
require_relative "style/rbs_inline/require_rbs_inline_comment"
require_relative "style/rbs_inline/struct_class_comment_alignment"
require_relative "style/rbs_inline/struct_new_with_block"
require_relative "style/rbs_inline/unmatched_annotations"
require_relative "style/rbs_inline/untyped_instance_variable"
require_relative "style/rbs_inline/variable_comment_spacing"
